### PR TITLE
fix: compile renderer separately due to import issues

### LINKED ISSUE #27: Uncaught ReferenceError: exports is not defined
Thanks for updating this repository to use the newest version of Electron. I was trying to use it but I have a problem with React. When I try to import I get the `Uncaught ReferenceError: exports is not defined`. I've tried several solutions found on Stackoverflow and GitHub but nothing works. I've also tried `nodeIntegration: true` but it doesn't seem to work either. It exposes `window.require` function but it doesn't add `module.exports`. I don't know what's wrong with that.

### PR DESCRIPTION
**Pull request by malept**
This should fix #27.

The problem is that currently, `tsconfig.json` specifies that `compilerOptions.module` is `commonjs`, which is Node.js specific (converts `import` to `require`). As Chromium doesn't understand `require` (unless you turn on `nodeIntegration` :grimacing:), we need to compile the renderer code separately from the main/preload code, and have it use `es2015` style modules, which Chromium does support (assuming you use `<script type="module">`).

Here are the changes:

* Move `src/renderer.ts` to `src/renderer/index.ts` so that it's easier to differentiate between main/preload and renderer code
* New `tsconfig.renderer.json` which compiles `src/renderer/` with `es2015` style module support
* Update the `build` script to run the `tsc` for renderer as well
* Add `concurrently` to `devDependencies` so `watch` still works (runs both `tsc -w` as appropriate)
* The renderer `<script>` tag is now `type="module"`

If this is approved, I'll port the change over to Electron Forge as well.

### CODE REVIEW

**Comment by StaticBR** [comment]
@malept  / @erickzhao  
Would be nice if you could merge this PR, since the quick starter is not really practical if typescript imports within the renderer are not working.  
Thank you.

**Comment by malept** [comment]
I'm not going to merge this without a review from @electron/wg-ecosystem .

In the meantime, nothing's stopping you from copying the files from this PR/branch.

**Review by erickzhao — CHANGES_REQUESTED** [review]
Don't think this solves the issue. I have a repro branch where I attempted to import React into the renderer.

* With the default settings in this PR: `This module is declared with using 'export =', and can only be used with a default import when using the 'esModuleInterop' flag.`
* If I turn `esModuleInterop` on, I get the same DevTools console error as before.

See code: https://github.com/electron/electron-quick-start-typescript/tree/erick/not-good-repro

**Comment by ProfXwing** [comment]
The status of this pull request has left me, frankly, confused. Perhaps you don't understand the purpose of the pull request, @erickzhao? 
As I understand it, this is not meant for you to be able to import node modules into the renderer. That isn't possible in the current master branch anyway (which you should have seen, considering your not-good-repro branch was on master, not this request, for whatever reason). This request allows the user to create their own renderer ts files (as many as they want), and import between *themselves*. So, for example, I can export a function from my dialogs.ts file and import it in my renderer.ts file, which isn't currently possible due to commonjs. 
This request adds a second tsconfig file that compiles the renderer files into es2015, which is necessary for chromium to understand. 

Or, perhaps I am completely wrong, in which case, pardon my necro and my ping. I truly believe this should be accepted, though. If it's of use, here's my fork of the current master branch with the changes in this request. https://github.com/ProfXwing/electron-quick-start-typescript

**Comment by ferminc** [comment]
I tried to use your code and it's not working for me, it won't compile the renderer folder

**Comment by ProfXwing** [comment]
@ferminc I assume this is in response to my code? I am unsure as to why it wouldn't compile the renderer folder. Did you make any changes from my repo?

Try this and see if it works:
git clone https://github.com/ProfXwing/electron-quick-start-typescript.git
cd electron-quick-start-typescript
npm i
npm start

If that compiles and runs as intended, try to note what change you make where things start to go wrong, and I can try to help you with that. I've made several changes from my template in my actual project (specific changes that shouldn't be added to the template).

**Pull request closed without merging**
